### ISSUE TITLE
Autosetup: infinite Searching for terrain

### ISSUE THREAD

**Issue by H4K0N42** [CuukyOfficial/VaroPlugin#87]
Plugin is on newest version and the server is on 1.20.2, this is the autosetup config:
```yml
border: 20002
enabled: true
lobby:
  enabled: true
  snap:
    type: MAX_HEIGHT
    ground:
      offset: 0
    maxHeight:
      offset: 50
    absolute:
      ypos: 64
  schematic:
    enabled: false
    file: plugins/Varo/schematics/lobby.schematic
  generated:
    height: 10
    width: 25
portal:
  enabled: true
  height: 5
  width: 4
spawns:
  amount: 40
  block:
    material: STONE_BRICK_SLAB
  radius: 9500
  sideblock:
    material: GRASS_BLOCK
autostart:
  time:
    hour: -1
    minute: -1
spawnGeneratorYTolerance: 42
```
The border is 10.000 blocks from 0 in each direction, the spawn radius should be 9.500. From what I see the cords at ~50.000, ~50.000 get checked now.

Some console output:
![image](https://github.com/CuukyOfficial/VaroPlugin/assets/78751562/221bd6c5-61be-4691-9e9e-0d67ea9a529e)
![image](https://github.com/CuukyOfficial/VaroPlugin/assets/78751562/4976205e-27f1-4d52-ae25-46e9feaf71a0)
![image](https://github.com/CuukyOfficial/VaroPlugin/assets/78751562/63840bd9-a6e0-4a08-aaa7-736463df2fdc)
