### ISSUE TITLE
People can rejoin after their playing time (not as spectators)

### ISSUE THREAD

**Issue by wheatley2056** [CuukyOfficial/VaroPlugin#92]
We are currently running a project with the plugin and have the bug that people can still return to the server after their playing time even though they are set to have only one session per day.

joinsystems.yml
```
catchUpSessions: false
ignoreJoinSystemsAsOP: true
joinAfterHours: -1
kickAtServerClose: false
massRecordingTime: 15
onlyJoinBetweenHours: true
onlyJoinBetweenHoursHour1: 15
onlyJoinBetweenHoursMinute1: 0
onlyJoinBetweenHoursHour2: 23
onlyJoinBetweenHoursMinute2: 0
preProduceSessions: 0
sessionsPerDay: 1
```

main.yml
```
dailyBackups: true
nametags:
  enabled: true
  visible:
    default: true
    team: true
    spectator: true
playTime: 20
prefix: '&7[&3LATEST&7]'
projectname: LATEST
projectnameColorcode: '&3'
language:
  main: de_de
  allowOther: true
crackedServer: false
resetSessionHour: 15
scoreboard: true
actionbar: true
supportPluginAds: false
unregisteredPlayerJoin: true
unregisteredPlayerJoinDuringGame: false
```
